### PR TITLE
Document inherited methods

### PR DESCRIPTION
**Pull request by fredemmott**
Breaking change: the index needs to retain and expose the full
data, not just the strings.

refs hhvm/user-documentation#1125

### CODE REVIEW

**Comment by fredemmott** [comment]
# Before

Screen Shot 2021-12-17 at 3 04 31 PM

# After

Screen Shot 2021-12-17 at 4 50 10 PM
Screen Shot 2021-12-17 at 4 50 12 PM
Screen Shot 2021-12-17 at 4 50 26 PM

No automated tests as there aren't currently any for this repo. That should be fixed - but is also mostly covered by docs.hhvm.com's test suite.

**Comment by AndrewDiMola** [comment]
Wow, this is awesome. Actually referencing the interface methods is definitely helpful... Was looking at this a while back but wasn't sure how to do it.

**Comment by AndrewDiMola** [comment]
while you're here... is there an easy enough way to link the interfaces on the `implements` line?

**Comment by fredemmott** [comment]
Not if we keep the syntaxc highlighting - but that's kinda broken already (and disabled in this example)

**Pull request merged**
