### PR TITLE
Require 4.80, use GitHub actions

### PR DESCRIPTION
**Pull request by fredemmott**
Without constraining dependencies like this, we end up picking earlier
    versions of e.g. hhast, hacktest that depend on HSL IO, but are older
    than the `hsl-io` virtual package.

    Additionally, bump up from 4.58 as hsl-experimental 4.58 actually
    requires 4.59 (my bad...). Go straight to the next LTS as everything in
    between is unsupported.

### CODE REVIEW

**Comment by fredemmott** [comment]
Test run here: https://github.com/fredemmott/hh-apidoc-1/actions/runs/499740392

**Comment by fredemmott** [comment]
Two reasons for failures:
- hhast doesn't match
- we're not rendering markdown correctly

**Comment by fredemmott** [comment]
markdown: v1.6.5 is a breaking change if HTML or links are used - setSourceType() must be used on the parser context

**Review by jjergus — APPROVED** [review]
Thanks!

I'm working on the hhast schema update now, almost have it ready.

**Comment by fredemmott** [comment]
> I'm working on the hhast schema update now, almost have it ready.


:/ just saw this, I just pushed this to master hopefully

**Comment by fredemmott** [comment]
Re-run at https://github.com/fredemmott/hh-apidoc-1/actions/runs/499763093 ; if that doesn't pick up the new hhast release I'll try again shortly

**Comment by fredemmott** [comment]
Merging: passed on 4.80 and 4.93; re-running, as nightly build failed as it had the old hhast cached

**Pull request merged**
